In [ ]:
import cv2

In [ ]:
cv2.__version__

'4.5.5'

In [ ]:
#import numpy as np
#from google.colab.patches import cv2_imshow                   for colab

In [ ]:
input = cv2.imread('woman-1979272_1920.jpg')
cv2.imshow('Image', input)#for jupyter
#cv2_imshow(input)# The first parameter will be title shown on image window,The second parameter is the image varialbe
# 'waitKey' allows us to input information when an image window is open
# By leaving it blank it just waits for anykey to be pressed before
# continuing. By placing numbers (except 0), we can specify a delay for
# how long you keep the window open (time is in milliseconds here)
cv2.waitKey()
# This closes all open windows
# Failure to place this will cause your program to hang
cv2.destroyAllWindows()

In [ ]:
input.shape

(1280, 1920, 3)

In [ ]:
# Let's print each dimension of the image

print('Height of Image:', int(input.shape[0]), 'pixels')
print('Width of Image: ', int(input.shape[1]), 'pixels')

Height of Image: 1280 pixels
Width of Image:  1920 pixels


In [ ]:
# Simply use 'imwrite' specificing the file name and the image to be saved
cv2.imwrite('output.jpg', input)
cv2.imwrite('output.png', input)

True

# Face & Eye Detection using HAAR Cascade Classifiers

In [ ]:
import numpy as np
import cv2

# We point OpenCV's CascadeClassifier function to where our
# classifier (XML file format) is stored
#face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')
# Load our image then convert it to grayscale
image = cv2.imread('depositphotos_102766834-stock-photo-group-of-business-people-in.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# Our classifier returns the ROI(range of interest)of the detected face as a tuple
# It stores the top left coordinate and the bottom right coordiantes
faces = face_classifier.detectMultiScale(gray,scaleFactor= 1.3,minNeighbors= 5)
# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No faces found")
# We iterate through our faces array and draw a rectangle
# over each face in faces
print(faces)
for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w,y+h), (127,0,255), 2)
    cv2.imshow('Face Detection', image)
    #cv2_imshow(image)
    cv2.waitKey(0)

cv2.destroyAllWindows()


[[700  78 134 134]
 [183  92 113 113]
 [482  84 127 127]
 [840 107 126 126]
 [356 135 107 107]
 [ 23 129 130 130]
 [269 250 124 124]
 [584 256 124 124]]


# Let's combine face and eye detection

In [ ]:
import numpy as np
import cv2

face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_eye.xml')

img = cv2.imread('depositphotos_102766834-stock-photo-group-of-business-people-in.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray, 1.3, 5)

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No Face Found")
print(faces)
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(127,0,255),2)
    cv2.imshow('img',img)
    cv2.waitKey(0)
    roi_gray = gray[y:y+h, x:x+w]  #crop face rectangle
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(255,255,0),2)
        cv2.imshow('img',img)
        cv2.waitKey(0)

cv2.destroyAllWindows()

[[700  78 134 134]
 [183  92 113 113]
 [482  84 127 127]
 [840 107 126 126]
 [ 23 129 130 130]
 [356 135 107 107]
 [269 250 124 124]
 [584 256 124 124]]


# Let's make a live face & eye detection, keeping the face inview at all times

In [ ]:
import cv2

# Loading the cascades
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_eye.xml')

# Defining a function that will do the detections
def detect(gray, frame):
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.1, 3)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0, 255, 0), 2)
    return frame

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = detect(gray, frame)
    cv2.imshow('Video', canvas)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()


# Car & Pedestrian Detection

In [ ]:
import cv2
import numpy as np

# Create our body classifier
body_classifier = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_fullbody.xml')

# Initiate video capture for video file
cap = cv2.VideoCapture('walking (1).avi')

# Loop once video is successfully loaded
while cap.isOpened():

    # Read first frame
    ret, frame = cap.read()
    #frame = cv2.resize(frame, None,fx=0.5, fy=0.5, interpolation = cv2.INTER_LINEAR)

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Pass frame to our body classifier
    bodies = body_classifier.detectMultiScale(gray, 1.2, 3)

    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 255), 2)
        cv2.imshow('Pedestrians', frame)

    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
# OpenCV Python program to detect cars in video frame
# import libraries of python OpenCV
import cv2

# capture frames from a video
cap = cv2.VideoCapture( 'cars.mp4')

# Trained XML classifiers describes some features of some object we want to detect
car_cascade = cv2.CascadeClassifier( 'cars.xml')

# loop runs if capturing has been initialized.
while True:
    # reads frames from a video
    ret, frames = cap.read()
    # convert to gray scale of each frames
    gray = cv2.cvtColor(frames, cv2.COLOR_BGR2GRAY)
    # Detects cars of different sizes in the input image
    cars = car_cascade.detectMultiScale( gray, 1.1, 1)
    # To draw a rectangle in each cars
    for (x,y,w,h) in cars:
        cv2.rectangle(frames,(x,y),(x+w,y+h),(0,0,255),2)
        # Display frames in a window
        cv2.imshow('Car Detection', frames)
    # Wait for Enter key to stop
    if cv2.waitKey(33) == 8:
        break

cv2.destroyAllWindows()

# Capture and mouse draw rectangle from webcam and sketch process it on a live feed

In [ ]:
import cv2
from matplotlib import pyplot as plt
import numpy as np

In [ ]:
def sketch_transform(image):
    image_grayscale = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    image_grayscale_blurred = cv2.GaussianBlur(image_grayscale, (7,7), 0)#for smoothning
    image_canny = cv2.Canny(image_grayscale_blurred, 10, 80)#edge detection
    _, mask = image_canny_inverted = cv2.threshold(image_canny, 30, 255, cv2.THRESH_BINARY_INV)#assignment of pixel values in relation to the threshold value provided
    return mask

In [ ]:
cam_capture = cv2.VideoCapture(0)
cv2.destroyAllWindows()

while True:
    _, im0 = cam_capture.read()
    showCrosshair = False
    fromCenter = False
    r = cv2.selectROI("Image", im0, fromCenter, showCrosshair)
    break

while True:
    _, image_frame = cam_capture.read()

    rect_img = image_frame[int(r[1]):int(r[1]+r[3]), int(r[0]):int(r[0]+r[2])]

    sketcher_rect = rect_img
    sketcher_rect = sketch_transform(sketcher_rect)

    #Conversion for 3 channels to put back on original image (streaming)
    sketcher_rect_rgb = cv2.cvtColor(sketcher_rect, cv2.COLOR_GRAY2RGB)

    #Replacing the sketched image on Region of Interest
    image_frame[int(r[1]):int(r[1]+r[3]), int(r[0]):int(r[0]+r[2])] = sketcher_rect_rgb

    cv2.imshow("Sketcher ROI", image_frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cam_capture.release()
cv2.destroyAllWindows()